services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: message_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: message_service_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  messageservice:
    image: ghcr.io/rrrinat/message_service:latest 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=message_service_db;Username=message_user;Password=123
    ports:
      - "5009:80"
    depends_on:
      - db
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  messagesenderclient:
    image: ghcr.io/rrrinat/message_sender_client:latest 
    depends_on:
      - messageservice
    environment:
      - SERVER_URL=http://messageservice:80/api/messages
    ports:
      - "5000:80"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  messagereceiverclient:
    image: ghcr.io/rrrinat/message_receiver_client:latest
    depends_on:
      - messagesenderclient
    environment:
      - SERVER_WEBSOCKET_URL=ws://messageservice:80/ws
    ports:
      - "5001:80"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  messagehistoryclient:
    image: ghcr.io/rrrinat/message_history_client:latest
    depends_on:
      - messageservice
    environment:
      - SERVER_URL=http://messageservice:80/api/messages
    ports:
      - "5002:80"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
